name: folding-at-home

networks:
  proxy:
    external: true

volumes:
  folding-at-home-data:
    name: folding-at-home-data

services:
  foldingathome:
    image: lscr.io/linuxserver/foldingathome:8.5.5@sha256:af600a904da78b3deb67531da23ac47625ca59d50dd562d8cb0c0b34d873650f
    container_name: folding-at-home
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - ACCOUNT_TOKEN=${FOLDING_AT_HOME_ACCOUNT_TOKEN}
      - MACHINE_NAME=folding-at-home
    volumes:
      - folding-at-home-data:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 7396:7396