name: folding-at-home

networks:
  proxy:
    external: true

volumes:
  folding-at-home-data:
    name: folding-at-home-data

services:
  foldingathome:
    image: lscr.io/linuxserver/foldingathome:8.4.9@sha256:562e542f00c784ab3d9c3b0f57171d27fba12af27a751a93027d00127b4b1f4f
    container_name: folding-at-home
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - ACCOUNT_TOKEN=${FOLDING_AT_HOME_ACCOUNT_TOKEN}
      - MACHINE_NAME=folding-at-home
    volumes:
      - folding-at-home-data:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 7396:7396